if(${PROJECT_NAME}_ENABLE_SANITIZERS AND ${PROJECT_NAME}_ENABLE_TSAN)
  message(FATAL_ERROR "ENABLE_SANITIZERS (ASAN+UBSAN) and ENABLE_TSAN are mutually exclusive.")
endif()

if(${PROJECT_NAME}_ENABLE_SANITIZERS)
  if(NOT CMAKE_CXX_COMPILER_ID MATCHES "GNU|.*Clang")
    message(WARNING "Sanitizers only supported with GCC or Clang.")
    return()
  endif()
  add_compile_options(-fsanitize=address,undefined -fno-omit-frame-pointer -g)
  add_link_options(-fsanitize=address,undefined)
endif()

if(${PROJECT_NAME}_ENABLE_TSAN)
  if(NOT CMAKE_CXX_COMPILER_ID MATCHES "GNU|.*Clang")
    message(WARNING "TSan only supported with GCC or Clang.")
    return()
  endif()
  add_compile_options(-fsanitize=thread -fno-omit-frame-pointer -g)
  add_link_options(-fsanitize=thread)
endif()
