name: Lock Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pixi-lock-check:
    name: pixi/lock-check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0  # v0.9.5
        with:
          pixi-version: v0.63.2
      - name: Verify lockfile is up-to-date
        run: pixi install --locked
