name: Lock Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pixi-lock-check:
    name: pixi/lock-check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - uses: prefix-dev/setup-pixi@ba3bb36eb2066252b2363392b7739741bb777659  # v0.8.1
        with:
          pixi-version: v0.63.2
      - name: Verify lockfile is up-to-date
        run: pixi install --locked
